eqasim-org/ile-de-france

CHANGELOG.md, data/spatial/departments.py, matsim/runtime/eqasim.py, matsim/simulation/prepare.py
This PR introduces changes that update the dependency on `eqasim:1.0.6` and introduce changes that lead to a calibrated 5% output of the Île-de-France / Paris scenario. 
This includes the following:
- Making use of new standard values (5% replanning rate for mode choice)
- Making use of new utility estimators and pricing structure for Île-de-France
- Adjusting the capacity of links inside of Paris to 80% of the initial value (as pipeline output)
- Adding the `isUrban` attribute to activities and links, which is used in utility estimation
=> Consolidate calibrated Île-de-France / Paris scenario for 5% sample

.travis.yml, CHANGELOG.md, matsim/runtime/eqasim.py, synthesis/population/activities.py, synthesis/population/matched.py, synthesis/population/spatial/locations.py, synthesis/population/spatial/primary/candidates.py, synthesis/population/spatial/secondary/components.py, synthesis/population/spatial/secondary/locations.py, synthesis/population/spatial/secondary/problems.py, synthesis/population/spatial/secondary/rda.py
The idea would be that the "tails" or the complete "free chains" are handled as tours.
=> Activity chains that do not start/end at home

data/gtfs/utils.py
There was a weird error in the file encoding of the merged gtfs on windows... explicitly specifyiing the encoding to utf-8 fixes this issue
=> fix gtfs encoding on windows

CHANGELOG.md, data/gtfs/cleaned.py
The merged GTFS had an arbitrary order of weekdays (but pt2matsim expects ordered values from monday to sunday, see https://github.com/matsim-org/pt2matsim/pull/173). This bug only shows up if one selects explicitly one day from GTFS using `gtfs_date: 20220901` in the configuration. By default the day with most services is selected.
=> fix: Arbitrary order of week days in merged GTFS

data/hts/edgt_44/cleaned.py, data/hts/edgt_44/raw.py
Select people who : 
1. Fully awnsered the questionary (PENQ = 1) 
2. and made at least one trip (P19 = 1) 
3. or stayed at home (P19 =2)
All persons with PENQ == 1 match the 2 and 3 conditions but code is  written to make it explicit (counts :  all persons : 29496 ;  filtered persons : 20799)
=> fix: Properly treat non-movers in EDGT 44

CHANGELOG.md, data/hts/entd/raw.py
I noticed that the ENTD cleaning stage does not recognize the bike mode. So I fixed that by forcing the `str` type on the mode column in the reading stage.
The read of the ENTD consists of a reading stage (_data/hts/entd/raw.py_) and a cleaning stage (_data/hts/entd/cleaned.py_).
The reading stage uses the pandas' method `read_csv`. If not supplied, this method guesses the column types.
In particular, the column `V2_MTP` become of _float_. That means that all the trailing zeros are ignored.
This behavior becomes an issue when we expect these trailing zeros to stay when we cast it to the _string_ type.
In particular, here:
https://github.com/eqasim-org/ile-de-france/blob/0aac9f3699b19ff8be7e264b722ddbb1d229d236/data/hts/entd/cleaned.py#L180
We expect the bike mode to be "2.20"  : …
=> fix: Fix raw mode recognition in ENTD.

CHANGELOG.md, data/bpe/cleaned.py
In BPE 2021, some numbers have a comma ("`,`"). These break the pipeline when the lines where the commas are, are considered. For example, when you try to synthesize a population for Île-de-France.
Here is an example of trace when this is not fixed:
```
Traceback (most recent call last):
File "/home/aina/anaconda3/envs/population_synthesis/lib/python3.7/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/home/aina/anaconda3/envs/population_synthesis/lib/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/home/aina/anaconda3/envs/population_synthesis/lib/python3.7/site-packages/synpp/__main__.py", line 14, in <module>
synpp.run_from_yaml(config_path)
File "/home/aina/anaconda3/envs/population_synthesis/lib/python3.7/site-packages/synpp/pipeline.py" …
```
=> fix: Fix coordinates format (commas vs points) in BPE.

data/income/municipality.py, data/income/region.py, data/od/raw.py, data/spatial/codes.py, data/spatial/iris.py, data/spatial/population.py
To make the code more usable as it is and to progress in line with the generalization of the pipeline (https://github.com/eqasim-org/ile-de-france/issues/139), I suggest adding the parameters below. It should also simplify the update of the input files.
- `income_com_path` (default: `filosofi_2015/FILO_DISP_COM.xls`),
- `income_reg_path` (default : `filosofi_2015/FILO_DISP_REG.xls`),
- `income_year` because the income year is needed to parse the column names in FiLoSoFi data (default: `15`),
- `od_pro_path` (default: `rp_2015/FD_MOBPRO_2015.dbf`),
- `od_sco_path` (default: `rp_2015/FD_MOBSCO_2015.dbf`),
- `codes_path` (default: `codes_2017/reference_IRIS_geo2017.xls`),
- `iris_path` (default: `codes_2017/reference_IRIS_geo2017.xls`),
- `population_path` (default: …
=> feat: Add more configurable paths for input data.

CHANGELOG.md, data/hts/edgt_lyon/cleaned_cerema.py, data/hts/edgt_lyon/raw_cerema.py
Twin PR for #169 taking into account persons that have responded to the travel survey but stayed at home.
=> fix: Correct treatment of non-movers in CEREMA EDGT for Lyon

CHANGELOG.md, config_corsica.yml, config_lyon.yml, config_nantes.yml, config_toulouse.yml, data/bdtopo/output.py, data/bdtopo/raw.py, docs/cases/corsica.md, docs/cases/lyon.md, docs/cases/nantes.md, docs/cases/toulouse.md, docs/population.md, synthesis/locations/home.py, tests/testdata.py
Closes #178. To increase reproducibility of the pipeline, we now make use of stable and long-term available BD-TOPO data from 2022 (which will be updated annually). Since this data is only available on the department level, a new logic has been implemented: The pipeline expects the IGN files for the configured departments in the data folder (in `bdtopo22`). The user, hence, only needs to dump the correct files into that folder. As a nice side effect, this simplifies configuration for non-IDF scenarios.
=> feat: load BD-TOPO by department

CHANGELOG.md, synthesis/population/matched.py
I just noticed that in smaller machines, the parallelization of numba actually slows down the statistical matching (because it is already parallelized and numba will use multiple threads per process). But now this even lead to segfaults for some reason. So I just disabled the parallel mode for numba and things work fine and much faster on medium-sized machines.
=> fix: Resolve segfault in statistical matching

CHANGELOG.md, config_corsica.yml, config_lyon.yml, config_nantes.yml, config_toulouse.yml, data/bdtopo/raw.py, docs/cases/corsica.md, docs/cases/lyon.md, docs/cases/nantes.md, docs/cases/toulouse.md, docs/population.md, documentation/meta_output.py, tests/testdata.py
Proposal for #185: Read whatever is there in the `bdtopo_path` folder and filter out irrelevant departments on the go. Closes #185.
=> feat: Simplify management of BD-TOPO data

CHANGELOG.md, data/ban/raw.py, data/bdtopo/raw.py, data/gtfs/output.py, data/osm/cleaned.py, data/spatial/iris.py
At multiple points in the pipeline, we explore the files to read using `glob`. However, the order of `glob` is undefined, especially on different systems. This PR orders the explored files by name wherever `glob` is used. This is a potential fix for #202.
=> fix: read order for files discovered using glob

environment.yml
Update for dependencies:
- `py7zr=0.20.4` is not available anymore
- `sqlite=3.42.0` was an implicit dependency before, but conda selects a newer version that makes unit tests fail now
=> fix: conda dependencies

matsim/runtime/eqasim.py
Apparently, older versions of `git` (like on our HPC) don't know the `--filter` tag, so we rather go back to `--depth`.
=> fix: compatibility with older git

.github/workflows/tests.yml, docs/cases/corsica.md, matsim/runtime/eqasim.py, matsim/simulation/prepare.py, matsim/writers.py, synthesis/output.py, tests/test_determinism.py
The first PR was having problems testing so I re-created it here
This PR proposes the following enhancements:
- Generating a pt legs csv file during mode choice, allowing to directly analyze PT usage by the generated population
- When using the mode choice, the population routing is skipped since routing already happens during the mode choice. This required to write the trip mode in the routingMode attribute when converting the trips csv file to a MATSim plans file in the matsim.scenario.population stage. For that the matsim/writers.py script was changed a bit.
- Along the way the pipeline was updated to use Eqasim 1.5.0
=> Feat: Generating PT legs during mode choice + skipping routing during mode choice + update to Eqasim 1.5.0 (v2)

.github/workflows/data.yml, .github/workflows/tests.yml, docs/verify_data.py
- Previously, we were checking data availability at every PR, but it seems that INSEE doesn't like the number of requests and some of them are blocked. However, introducing a wait time would blow up the PR execution time.
- Therefore, the current PR should now change the behavior such that data availability is checked every Sunday at 10am.
=> chore: verify data availability using cronjob

CHANGELOG.md, matsim/output.py
We have some servers that manage to create the simulation data for a 10% sample, but then they don't manage to fit the mode choice in the two test iterations into memory. This PR adds a config option that allows disabling the previously obligatory run of two MATSim iterations before writing out the MATSim files.
=> feat: optionally not run MATSim

docs/population.md, environment.yml, synthesis/output.py
Add export for all outputs in parquet files. All existing exports are kept. New parquet files are added.
Parquet files use .parquet extension. And geospatial files use .geoparquet extension.
Pyarrow package dependency is added.
Parquet format is extremely faster to read than GeoPackage files and csv. For example on trips data on 10% population for departement 14, it takes 25 seconds to read in GeoPackage, and only 0.17 seconds in Parquet.
=> feat(output): export all outputs in parquet files

environment.yml, tests/test_determinism.py
For some reason, the environment runs well on Linux and Windows in CI, but it cannot be resolved on our Linux servers. Trying to update `pyarrow` here to check if it solves the problem (the indicated configuration works on our servers now). I have the feeling that the update of `sqlite` changed some unit tests before. Let's see what the automated tests say.
=> fix: update pyarrow to latest version

synthesis/population/spatial/primary/candidates.py, tests/test_determinism.py
I took the liberty of creating a PR that fixes #237. Running now to see if it has any impact on the unit tests.
=> fix: shuffling of primary location candidates

CHANGELOG.md, data/hts/hts.py
The cleaning logic for ENTD covered trips that are entirely contained in another trip along the chain of a person. Those trips (actually, there is only one in the whole data set) were deleted so far. However, this causes a problem when checking for the consistency of activity types along the chain later on. So far, we didn't notice this, because we never used the entire ENTD, but only filtered data sets for individual sets of departments. The problem is now fixed by squeezing the first trip to duration zero and setting departure time and arrival time to the departure time of the following trip.
=> fix: repair completely overlapping trips in ENTD

CHANGELOG.md, synthesis/population/spatial/secondary/locations.py, tests/test_determinism.py
The secondary location model got individual random seeds passed to every parallel process. However, so far, it was using the global random seed instead. This should not have a big impact as every thread processes different activity chains, but there may still be some minor effects in terms of correlations between similar activity chains that are now resolved.
=> fix: random seeds in secondary location model

CHANGELOG.md, data/hts/edgt_44/filtered.py, data/hts/edgt_lyon/filtered.py, data/hts/egt/filtered.py, data/hts/entd/cleaned.py, data/hts/entd/filtered.py
Link to issue #239 
- Boolean Parameter "filter_hts" to apply filtering on hts data; remove filtering by default with False
This apply to all hts data, do you agree ? 
- Without filter 1 inconsistent activity types data on ENTD data appears => added fix_activity_types function to entd/cleaned file to resolve this error.
=> feat : option param to remove filtering for requesting dep in hts

CHANGELOG.md, matsim/scenario/supply/osm.py
In recent versions of the pipeline the whole conversion of the OSM data plus transit matching was run again once the population home locations have changed. The reason was that we obtained the CRS from there. Now we obtain the right CRS from `data.spatial.iris` which does not change frequently.
=> fix: avoid regenerating network and transit when population changes

.github/workflows/tests.yml
Fixes #311. Enables caching of the conda environment for the Windows integration tests.
=> chore: conda cache for windows

matsim/scenario/population.py
Closes #122. If the eqasim `carAvailability` is `none`, we also add the attribute `carAvail` that is used by standard MATSim and set it to `never`.
=> feat: add carAvail attribute for standard MATSim

data/osm/cleaned.py
I'm cherry picking this change from this bigger PR https://github.com/eqasim-org/ile-de-france/pull/337. As I believe the MATSim part of the pipeline is unusable in without it as only the first municipality is red from the osm files :)
=> fix: properly filtering osm data

environment.yml, matsim/runtime/java.py
Update to `synpp` version `1.6.0` with the following major improvements:
- The new version allows passing config options via the command line, e.g., `--java_memory 20G` (see https://github.com/eqasim-org/synpp/pull/87)
- The new version allows defining stage options as `volatile` which makes it possible that a Java-based is not reevaluated if it has already run but you change the allowed memory via config (see https://github.com/eqasim-org/synpp/pull/86)
=> chore(deps): synpp-1.6.0

data/vehicles/types.py, synthesis/vehicles/cars/default.py, synthesis/vehicles/passengers/default.py, tests/test_determinism.py
related to this PR on the java side : https://github.com/eqasim-org/eqasim-java/pull/413
So the problem was that hbefa informations stored in the vehicleType was partially wrong. The `HbefaEmissionsConcept` was not in the right format, and the `HbefaSizeClass` was taken from HBEFA 3 database (now we are working with version 4). And since the chosen Hbefa lookup strategy has a fallback on average vehicle type (with little warning when it happens) it never broke anything. But the categories were never taken into account, and the results were all false (equivalent to a default vehicle fleet).
=> fix(vehicles): use valid hbefa keys for vehicle types
