CHANGELOG.md, docs/howto.md, environment.yml, matsim/runtime/git.py, matsim/runtime/java.py, matsim/runtime/maven.py
- Switch to Anaconda for default instructions
- Make runtime dependency errors more verbose
=> Runtime updates

CHANGELOG.md, data/gtfs/cleaned.py, data/gtfs/utils.py, docs/howto.md, docs/regions.md, matsim/scenario/supply/gtfs.py, tests/testdata.py
- Cut GTFS schedules to the scenario area automatically
- Make possible to merge multiple GTFS files automatically
=> Improve handling of GTFS data

CHANGELOG.md, matsim/simulation/prepare.py
=> Remove duplicate imputation of 'urban' attribute

CHANGELOG.md, synthesis/population/trips.py
The issue was due to the df_trips not being properly sorted.
=> Fix a bug where departure times can be negative

CHANGELOG.md, data/bpe/raw.py, docs/population.md, tests/testdata.py
=> Update to BPE 2019

docs/population.md
and that browsers cannot download it
Closes #72
=> Update Step 10 to reflect new address file

data/osm/cleaned.py
I allways had errors with relative paths here. This is a fix that I used successfully on both linux and windows.
=> fix osmosis path error

CHANGELOG.md, data/gtfs/utils.py, docs/cases/nantes.md
Fixing some details when using the ensemble of GTFS files of Nantes and neighboring networks.
=> Fix additional GTFS for Nantes

data/osm/cleaned.py, docs/cases/corsica.md, docs/cases/lyon.md, docs/cases/nantes.md, docs/cases/toulouse.md, docs/simulation.md, tests/testdata.py
=> docs: Fixed version of OSM data

data/osm/osmosis.py, matsim/runtime/git.py, matsim/runtime/java.py, matsim/runtime/maven.py
=> fix: Behaviour of shutil.which

CHANGELOG.md, data/bpe/cleaned.py, data/bpe/raw.py, docs/population.md, tests/testdata.py
- BPE is now delivered and read in CSV
- Fixing of coordinates is obsolete as all observations now have coordinates
- No inconsistencies for municipality codes
- Documentation and unit tests updated
Fixes #123. Fixes #105.
=> fix: Update to BPE 2021

data/vehicles/raw.py, environment.yml, environment_mamba.yml
It is the same issue as here : https://foss.heptapod.net/openpyxl/openpyxl/-/issues/1659
=> fix: Vehicles metadata format issue

data/sirene/raw_siren.py, tests/testdata.py
=> fix parsing law status

.github/workflows/tests.yml, CHANGELOG.md, docs/population.md, docs/simulation.md
- Update GH actions 
- Use prepackaged actions for Java and conda
=> chore: update GH actions

documentation/meta_output.py
=> fix: Update git commit in meta.json

.github/workflows/tests.yml, data/bpe/cleaned.py, data/census/cleaned.py, data/gtfs/utils.py, data/hts/edgt_44/cleaned.py, data/hts/edgt_lyon/cleaned_adisp.py, data/hts/edgt_lyon/cleaned_cerema.py, data/hts/egt/cleaned.py, data/hts/entd/cleaned.py, data/od/cleaned.py, documentation/shapes.py, synthesis/locations/education.py, synthesis/locations/home.py, synthesis/locations/work.py, synthesis/output.py, synthesis/population/matched.py, synthesis/population/sampled.py, synthesis/population/spatial/home/zones.py, tests/testdata.py
This PR will step by step eliminate current deprecation and other warnings from the code base.
=> chore: Eliminate warnings in the Python pipeline

environment.yml, tests/test_pipeline.py, tests/testdata.py
Adds unit tests for testing vehicle fleet sampling from vehicle stock data. Closes #221.
=> chore: unit tests for existing vehicle fleet sampling

synthesis/population/projection/ipu.py
- Before, IPU nearly converged, but not perfectly, because the weighting totals were not consistent. Since the RP data does never have all zero-year old persons, the upscaling would be very high for the projections. That's why we excluded "zero years" from the weighting targets. This, however, should also then affect the overall population total (excluding zero-year olds) which was not the case before.
- Now, the weighting is properly implemented, excluding the stratum of zero-year old people from the weighting process, as well as those that are 105+. IPU now converges by convergence criteria of a scaling factor of less than 0.1% and not only by the maximum iterations.
- Furthermore, made the whole process more verbose: we print the IPU process with the current update factors and then …
=> feat: improve handling of projections

matsim/scenario/supply/gtfs.py, matsim/scenario/supply/osm.py, matsim/scenario/supply/processed.py, synthesis/locations/home/addresses.py, synthesis/output.py, synthesis/population/spatial/locations.py, synthesis/population/spatial/secondary/locations.py
to be able to port the pipeline to other use cases more easily
=> chore: avoid hardcoding epsg codes outside of 'data' space

config_full.yml, full_config.yml
List all possible config options in one file.
I'm open to suggestions, what do you think ?
Todos : 
Fixes https://github.com/eqasim-org/ile-de-france/issues/271
=> feat: add a full config with all possible entries

analysis/synthesis/population.py
- Correction volume eqasim & purpose analysis
- Separation full and adjust volume for each analysis
Closes #285
=> fix(analysis): correct and improve population analysis

docs/simulation.md, matsim/runtime/java.py
closes: https://github.com/eqasim-org/ile-de-france/issues/306
=> chore: update Java version recommandation and check

data/gtfs/utils.py
Some GTFS might not have a location_type column in stops.txt though they are valid (e.g. Strasbourg's CTS GTFS); check if the column exists before using it
=> feat: handle GTFS without location types

.github/workflows/tests.yml, environment.yml, tests/test_determinism.py
Fixes #301. Updates versions of the geoprocessing stack (geopandas, fiona, ...) in the conda environment.
=> chore: update versions of geo processing stack

.github/workflows/release-please.yml
Updating the release token so that the tests will run for the release PRs
=> chore: update release token

docs/contents.md, docs/requirements.txt
- Some dependnecy problem just came up during documentation deployment
- Including the `cases` in the TOC
=> chore: fixes for docs

README.md, docs/population/population_data.md, docs/population/population_execution.md, docs/population_before.md
Some information got lost along the way to Sphinx. See #327. Closes #399.
=> docs: fix current state
